.

diff --git a/.github/workflows/test-action.yml b/.github/workflows/test-action.yml
--- a/.github/workflows/test-action.yml
+++ b/.github/workflows/test-action.yml
@@ -20,5 +20,5 @@ jobs:
       - name: Test the container
         if: ${{ steps.my-action.outputs.answer != 42 }}
         run: |
-        echo "::error file=entrypoint.sh,line=4,title=Error in container::The answer was not expected"
-        exit 1
+          echo "::error file=entrypoint.sh,line=4,title=Error in container::The answer was not expected"
+          exit 1
